const staticText = {
  bannerText: "save app for free",
  bannerButton: "download now",
  landingPageTitle: "free industry standard resumes",
  resumesCreated: "resumes created till date",
  newResume: "create new resume",
  existingResume: "share existing resume",
  name: "name *",
  mobile: "mobile Number *",
  email: "email address *",
  city: "city",
  pincode: "pincode",
  submitPersonalDetails: "next:education",
  closeModal: "close X",
  universityName: "school/university",
  degree: "qualification/degree",
  field: "field of study",
  startDate: "start date",
  endDate: "end date",
  detail: "details",
  delete: "delete",
  submitEducation: "next:experience",
  phd: "Phd/Doctors",
  masters: "masters(MA, ME, MS, MBA, etc.)",
  pgdm: "post-graduate diploma",
  graduation: "graduation",
  diploma: "diploma",
  tenthPlusTwo: "10 +2",
  tenth: "metric",
  edit:"edit",
  month:"month",
  year:"year",
  presentHere:"or i currently study here",
  period:"period",
  addEducation:"add education",
  save:"save"
};

export default staticText;
