const staticText = {
  bannerText: "save app for free",
  bannerButton: "download now",
  landingPageTitle: "free industry standard resumes",
  resumesCreated: "resumes created till date",
  newResume: "create new resume",
  existingResume: "share existing resume",
  name: "name *",
  mobile: "mobile number *",
  email: "email address *",
  city: "city",
  pincode: "pincode",
  submitPersonalDetails: "next:education",
  closeModal: "close X",
  universityName: "school/university",
  degree: "qualification/degree",
  field: "field of study",
  startDate: "start date",
  endDate: "end date",
  detail: "details",
  delete: "delete",
  submitEducation: "next:experience",
  phd: "Phd/Doctors",
  masters: "masters(MA, ME, MS, MBA, etc.)",
  pgdm: "post-graduate diploma",
  graduation: "graduation",
  diploma: "diploma",
  tenthPlusTwo: "10 +2",
  tenth: "metric",
  edit: "edit",
  month: "month",
  year: "year",
  presentHere: "or i currently study here",
  workHere:"or i currently work here",
  period: "period",
  save: "save",
  employerName: "employer name",
  designation: "designation",
  submitExperience: "almost there",
  profileDetail: "add/edit profile",
  educationDetail: "add/edit education",
  experienceDetail: "add/edit experience",
  socialLink: "add/edit social links",
  skill: "add/edit skills",
  courseDetail: "add/edit courses",
  awardDetail: "add/edit awards and honours",
  language: "add/edit languages",
  reference: "add/edit references",
  generateResume: 'generate resume',
  submit: "submit",
  linkedin: "linkedIn",
  instagram: "instagram",
  facebook: "facebook",
  github: "github",
  portfolio: "portfolio",
  searchSkill:"search skills",
  remove:"X remove",
  add:"add +",
  instituteName:"institute name",
  courseName:"course name",
  certificate:"certificate link",
  language:"language",
  proficiency:"proficiency",
  beginner:"beginner",
  intermediate:"intermediate",
  expert:"expert",
  companyName:"company name"
};

export default staticText;
