const staticText = {
  bannerText: "save app for free",
  bannerButton: "download now",
  landingPageTitle: "free industry standard resumes",
  resumesCreated: "resumes created till date",
  newResume: "create new resume",
  existingResume: "share existing resume",
  name: "name *",
  mobile: "mobile number *",
  email: "email address *",
  city: "city",
  pincode: "pincode",
  submitPersonalDetails: "next:education",
  closeModal: "close X",
  universityName: "school/university",
  degree: "qualification/degree",
  field: "field of study",
  startDate: "start date",
  endDate: "end date",
  detail: "details",
  delete: "delete",
  submitEducation: "next:experience",
  phd: "Phd/Doctors",
  masters: "Masters",
  pgdm: "Post-graduate diploma",
  graduation: "Graduation",
  diploma: "Diploma",
  tenthPlusTwo: "10 +2",
  tenth: "Metric",
  edit: "edit",
  month: "month",
  year: "year",
  presentHere: "or i currently study here",
  workHere:"or i currently work here",
  period: "period",
  save: "save",
  employerName: "employer name",
  designation: "designation",
  submitExperience: "almost there",
  personal: "add/edit personal detail",
  education: "add/edit education",
  experience: "add/edit experience",
  socialLink: "add/edit social links",
  skill: "add/edit skills",
  course: "add/edit courses",
  award: "add/edit awards",
  language: "add/edit languages",
  reference: "add/edit references",
  generateResume: 'generate resume',
  submit: "submit",
  linkedin: "linkedIn",
  instagram: "instagram",
  facebook: "facebook",
  github: "github",
  portfolio: "portfolio",
  searchSkill:"search skills",
  remove:"X remove",
  add:"add +",
  instituteName:"institute name",
  courseName:"course name",
  certificate:"certificate link",
  language_label:"language",
  proficiency:"proficiency",
  beginner:"Beginner",
  intermediate:"Intermediate",
  expert:"Expert",
  companyName:"company name",
  issuer:"issuer (or institute name)",
  title:"award title",
  issueDate:"issue date",
  download: "download resume"
};

export default staticText;
